server:
  port: 8085
logging:
  level:
    org.example.springexample: debug
comment:
  length:
    max: 300
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contact
    username: root
    password: 1eav
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: validate